// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Product struct {
	ID           string
	Title        string
	ProducerName string
	Value        int32
}

type Transaction struct {
	ID          string
	Type        int32
	Date        string
	ProductName string
	SellerName  string
	Value       int32
	CreatedAt   time.Time
}

type User struct {
	ID        string
	Name      string
	Balance   int32
	CreatedAt time.Time
}
